; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.1.3 on Thu Jun 18 2020 13:36:53 GMT-0500 (Central Daylight Time)
M280 P0 S10 ; deploy BLTouch

