; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v3.1.3 on Thu Jun 18 2020 13:36:54 GMT-0500 (Central Daylight Time)
G91                  ; relative positioning
G1 H2 Z5 F6000       ; lift Z relative to current position
G90                  ; absolute positioning
G1 X182.5 Y150 F6000 ; go to first probe point
M400                 ; wait for moves
G30                  ; home Z by probing the bed
G1 Z10 F6000         ; raise Z again

