; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.1.3 on Thu Jun 18 2020 13:36:53 GMT-0500 (Central Daylight Time)
M280 P0 S90 ; retract BLTouch

