; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Sat Jul 18 2020 16:35:39 GMT-0500 (Central Daylight Time)

M291 P"Executing tpost0.g" S0 T5