; homey.g
; called to home the Y axis
;
; generated by RepRapFirmware Configuration Tool on Thu Jul 20 2017 18:24:16 GMT-0500 (CDT)

; Go into relative mode; Lower Z relative to current position
G91
G1 Z+5 F6000

; Move quickly to Y axis endstop and stop there (first pass)
G1 Y320 F1800 S1

; Go back a few mm
G1 Y-5 F6000

; Move slowly to & axis endstop once more (second pass)
G1 Y320 F360 S1

; Lift Z again
G1 Z-5 F6000

; Back to absolute mode
G90
